Repository dwyl/gitea, pull requests merged in 2022-05, with the labels that each got.

#4 Gogs to gitea
  .env_sample
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  README.md
  config/config.exs
  config/test.exs
  coveralls.json
  lib/git_mock.ex
  lib/gitea.ex
  lib/helpers.ex
  lib/http.ex
  lib/httpoison_mock.ex
  mix.exs
  mix.lock
  test-repo/README.md
  test/git_mock_test.exs
  test/gitea_helpers_test.exs
  test/gitea_http_test.exs
  test/gitea_test.exs
  test/httpoison_mock_test.exs
  test/test_helper.exs
Labels: in-review

#9 Update intro image from Gogs to Gitea logo
  README.md
Labels: awaiting-review

#10 update intro diagram #1
  README.md
Labels: awaiting-review

#8 Create org
  lib/gitea.ex
  lib/http.ex
  lib/httpoison_mock.ex
  test/gitea_test.exs
  test/httpoison_mock_test.exs
Labels: question, in-review

#13 Extract org name and repo name from url
  README.md
  lib/helpers.ex
  mix.exs
  test/httpoison_mock_test.exs
Labels: awaiting-review

#11 Update docs issue #1
  .gitignore
  .gitmodules
  README.md
  lib/helpers.ex
  mix.exs
  test-repo/README.md
  test/gitea_helpers_test.exs
  test/gitea_test.exs
  tmp/test-repo/README.md
Labels: in-review

#20 Add auto_init value in create repo body request
  lib/gitea.ex
  mix.exs
Labels: awaiting-review

#26 PR: Create Custom Exception
  README.md
  coveralls.json
  lib/error.ex
  lib/gitea.ex
  mix.exs
  test/gitea_error.exs
  test/gitea_test.exs
  tmp/test-repo/README.md
Labels: help wanted, in-review

#23 PR: Add feature `clone/2`
  lib/gitea.ex
  lib/helpers.ex
  mix.exs
  test/gitea_test.exs
Labels: awaiting-review

#27 Parse message error
  lib/gitea.ex
  lib/http.ex
  lib/httpoison_mock.ex
  mix.exs
  test/gitea_test.exs
Labels: awaiting-review

#31 Git dir
  lib/gitea.ex
  lib/helpers.ex
  mix.exs
  test/gitea_test.exs
Labels: awaiting-review

#33 Commit errors
  lib/gitea.ex
  mix.exs
  test/gitea_test.exs
Labels: awaiting-review

#40 Update test for `temp_dir/1`
  lib/helpers.ex
  mix.exs
  test/gitea_helpers_test.exs
Labels: awaiting-review

#38 Create branch and switch branch
  lib/gitea.ex
  mix.exs
  test/gitea_test.exs
Labels: enhancement, in-review
